### PR TITLE
Fix broken links in ckcp docs

### PR DESCRIPTION
**Pull request by lcarva**
Signed-off-by: Luiz Carvalho <lucarval@redhat.com>

### CODE REVIEW

**Review by Roming22 — APPROVED** [review]

**Comment by lcarva** [comment]
/retest

Seems like a random issue?
```
 ++ oc whoami
Unable to connect to the server: dial tcp 184.169.249.38:6443: i/o timeout
+ echo '[ERROR] User '\'''\'' does not have the required '\''cluster-admin'\'' role.'
[ERROR] User '' does not have the required 'cluster-admin' role. 
```

**Comment by bnallapeta** [comment]
Thanks @lcarva for the fix :)

**Pull request merged**
