### PR TITLE
fixed issue of stonesoup e2e

### PR DESCRIPTION
**Pull request by xinredhat**
Because [PR](https://github.com/redhat-appstudio/e2e-tests/pull/397) introduces [2 new environment variables](https://github.com/redhat-appstudio/e2e-tests/pull/397/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5) that are required for bootstrapping a cluster via e2e-tests repo. We need to add the 2 new environment variables accordingly in [stonesoup-e2e-test](https://github.com/openshift-pipelines/pipeline-service/blob/main/.tekton/stonesoup-e2e-test.yaml) CI

### CODE REVIEW

**Comment by xinredhat** [comment]
I verified it and it worked well . It's ready for review

**Review by Roming22 — APPROVED** [review]

**Pull request merged**
