### PR TITLE
Enable completed_run_grace_period for tekton-results

### PR DESCRIPTION
**Pull request by Roming22**
Delete PipelineRuns 10 minutes after completion.

### CODE REVIEW

**Comment by enarha** [comment]
The way I read the documentation https://tekton.dev/docs/operator/tektonconfig/#note both `disabled: false` AND `schedule:` with empty value are required to disable the Tekton pruner. That does not make much sense and it looks more like a documentation issue, but I'm rising it anyway. If you have tested the above configuration and it disabled the pruner, then we are good.

**Comment by Roming22** [comment]
> The way I read the documentation https://tekton.dev/docs/operator/tektonconfig/#note both `disabled: false` AND `schedule:` with empty value are required to disable the Tekton pruner. That does not make much sense and it looks more like a documentation issue, but I'm rising it anyway. If you have tested the above configuration and it disabled the pruner, then we are good.

@enarha In this case the key value is `disabled: true`. So I do not think the note applies.

**Pull request merged**
