### PR TITLE
Fix pipeline webhook validation error

### PR DESCRIPTION
**Pull request by sayan-biswas**
Include tekton pipelines webhook validation fix from downstream tekton results

### CODE REVIEW

**Review by gabemontero — APPROVED** [review]
yep tracks with the commit just merged in https://github.com/openshift-pipelines/tektoncd-results/commits/downstream-0.7.0-01

**Comment by enarha** [comment]
@sayan-biswas You need to update line 6 as well.
Strangely GitHub does not allow me to comment on a line which is not changed in the PR. @gabemontero you please confirm that?

**Comment by sayan-biswas** [comment]
Lost some time in the CI for this.. 😣

**Comment by gabemontero** [comment]
same results issue on the latest downgrade test https://console-openshift-console.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/k8s/ns/tekton-ci/tekton.dev~v1beta1~PipelineRun/pipeline-service-upgrade-test-mtrr8/logs/tests-downgrade @sayan-biswas @Roming22 
```
[results]
  - Run pipeline: OK
  - Results in database:
    - Test records: Failed
[ERROR] Unable to retrieve records for 8a01f1c3-bee1-45c6-8add-3d6d6efc0c27 from pipeline run pipelinerun.tekton.dev/test-pipelinerun-pgvj8
```

The prior speculation I recall from @sayan-biswas is that a timing issue with pruning is the culprit.  Certainly we have seen this across many PRs @Roming22 so I'm going to merge this, so we can get going on the staging update.

That said, it is happening enough IMO that we should open a tracker that include figuring out, we don't know already @Roming22, how to run the upgrade / downgrade locally, and debug this live, as debugging post mortem is proving too difficult.

I'll bring this up on Thursday's standup.

**Comment by sayan-biswas** [comment]
@gabemontero Yes, this is showing up often now, and the fact that it is mostly happening in the upgrade tests warrants an investigation. If I get the bandwidth I'll look into it in this sprint.

**Pull request merged**
