### PR TITLE
update PAC to 0.15.0

### PR DESCRIPTION
**Pull request by ramessesii2**
* Locally tested ✔️,  `pipeline-service` argocd application is green in Argo CD Dashboard with PAC v0.15.0.
 
Signed-off-by: Satyam Bhardwaj <sabhardw@redhat.com>

### CODE REVIEW

**Comment by ramessesii2** [comment]
The same PR has been merged in infra-deployments - https://github.com/redhat-appstudio/infra-deployments/pull/1093

**Comment by Mo3m3n** [comment]
you will need to update the dependencies readme

**Comment by ramessesii2** [comment]
@Mo3m3n Did you mean [this](https://github.com/openshift-pipelines/pipeline-service/blob/main/shared/config/dependencies.sh) file? PAC is not mentioned there though.

**Comment by Mo3m3n** [comment]
This one https://github.com/openshift-pipelines/pipeline-service/blob/main/DEPENDENCIES.md

**Comment by ramessesii2** [comment]
Thanks @Mo3m3n, and done.

**Review by Roming22 — APPROVED** [review]

**Pull request merged**
