### PR TITLE
Upgrade OSP to 1.13

### PR DESCRIPTION
**Pull request by Roming22**
rh-pre-commit.version: 2.0.3
rh-pre-commit.check-secrets: ENABLED

### CODE REVIEW

**Comment by Roming22** [comment]
infra-deployments tests are green: https://github.com/redhat-appstudio/infra-deployments/pull/2921

**Comment by Roming22** [comment]
@enarha @ramessesii2 Please review and merge if you're OK with the change.
I've linked to the infra-deployment PR that test the change (tests are OK). I think we're all set.

**Review by enarha — COMMENTED** [review]
/lgtm

**Review by ramessesii2 — APPROVED** [review]

**Pull request merged**
