### PR TITLE
Cleanup minio tenant config

### PR DESCRIPTION
**Pull request by AndrienkoAleksandr**
# What doest this pull request do

Cleanup Minio.
Remove console service, because it is disabled.
Remove skip validation workaround for ArgoCD storage app.

### CODE REVIEW

**Review by Roming22 — CHANGES_REQUESTED** [review]

**Comment by Roming22** [comment]
Tagging the PR as `HOLD`. It only impacts local dev, so it can be merged during the freeze period. However we have important PRs going through at the moment, and I want to limit changes to the repository until they went through.

**Comment by AndrienkoAleksandr** [comment]
@xinredhat I see that, Minio on the Openshift was updated from 4.8 to 5.0.3, so maybe this bug was fixed... But will see...

**Comment by AndrienkoAleksandr** [comment]
Green.
/retest

**Comment by AndrienkoAleksandr** [comment]
Green
/retest

**Comment by AndrienkoAleksandr** [comment]
Green
/retest

**Comment by AndrienkoAleksandr** [comment]
Green
/retest

**Comment by AndrienkoAleksandr** [comment]
Green
/retest

**Comment by AndrienkoAleksandr** [comment]
Green
/retest

**Comment by AndrienkoAleksandr** [comment]
All Green, except destroy-cluster
--
[destroy-cluster](https://console-openshift-console.apps.pipeline-stage.3jhu.p1.openshiftapps.com/k8s/ns/pipeline-service-ci/tekton.dev~v1beta1~PipelineRun/pipeline-service-test-vg7nl/logs/destroy-cluster)

/retest

**Comment by AndrienkoAleksandr** [comment]
Green. @xinredhat I executed ci about 12 times, I don't see any minio failing. So I give up for now. I guess this issue was fixed with newer Minio...

**Comment by xinredhat** [comment]
> Green. @xinredhat I executed ci about 12 times, I don't see any minio failing. So I give up for now. I guess this issue was fixed with newer Minio...

@AndrienkoAleksandr thanks for the update.

**Comment by Roming22** [comment]
@AndrienkoAleksandr There's a pending comment. Once you've processed it, remove the draft label if this PR is ready to be merged.

**Comment by AndrienkoAleksandr** [comment]
@Roming22 I handled your feedback

**Review by Roming22 — APPROVED** [review]

**Pull request merged**
