### PR TITLE
Disable Tekton Results DB auto migration

### PR DESCRIPTION
**Pull request by enarha**
With the existing DB, it's causing a failure in api. Pod does not start.

### CODE REVIEW

**Review by adambkaplan — APPROVED** [review]
/approve

/lgtm

Disabling auto migration should not impact the service. Pods are currently crashlooping because the migration logic fails on apiserver start.

**Comment by adambkaplan** [comment]
/retest

Known "failed to list pods" flake.

**Review by Roming22 — APPROVED** [review]

**Comment by enarha** [comment]
Yes, we figured that earlier and that's why we moved to the "revert" strategy. I'm closing this PR.

**Pull request closed without merging**
