### PR TITLE
update tekton results

### PR DESCRIPTION
**Pull request by avinal**
https://github.com/openshift-pipelines/tektoncd-results/tree/downstream-0.7.0-02

### CODE REVIEW

**Review by gabemontero — APPROVED** [review]
I can at least confirm the commit matches downstream-0.7.0-02

I'll defer to @enarha and @sayan-biswas on a more detailed review

Once they are happy, and the tests are OK, I can merge is none of you have the merge button.

**Comment by enarha** [comment]
The change is LGTM. I've already reviewed the sync of the upstream changes and lgtm-ed it as well.

**Comment by enarha** [comment]
@gabemontero feel free to merge once the CI pass or I'll do it myself if it happens soon.

**Comment by Roming22** [comment]
Tests are failing during cluster install with `Error from server (Forbidden): pods "tekton-results-api-6999cbc689-2thvh" is forbidden: User "system:serviceaccount:pipeline-service:pipeline-service-manager" cannot get resource "pods/log" in API group "" in the namespace "tekton-results"`.

Maybe you need to add extra RBACs to the pipeline-service-manager SA?

**Comment by avinal** [comment]
I misunderstood, it is referring to `pods/log` but I cannot understand why that is required. However, I have made the changes and waiting for the results.

**Pull request merged**
