### PR TITLE
assign values to  `sync-wave`explicitly in manifests

### PR DESCRIPTION
**Pull request by ramessesii2**
#### This pull request introduces an explicit assignment of the default value (0) for sync-waves in our GitOps workflow. Currently, sync-waves are automatically allocated with a default value, but this change aims to enhance code readability and maintainability.

### CODE REVIEW

**Comment by gabemontero** [comment]
yes we can ignore the Red Hat Trusted App Pipeline failures for now

however, it is unclear to me if the PIpelines As Code CI / pipeline-serivce-upgrade-test failures are unrelated or not.

There is a failure in the results test.  Not sure that it is just a flake.

I think perhaps @ramessesii2 that you should work with @avinal and @sayan-biswas to either set up this branch locally and run the upgrade test locally to diagnose, or you use Romain's method for keeping the test cluster alive so that you three can debug.

**Comment by gabemontero** [comment]
based on what I just saw in Priti's PR, maybe the results failure is unrelated / intermittent

let's see 

/retest

**Comment by ramessesii2** [comment]
The same RESULTS error : 
```
task tests-downgrade has the status "Failed":

OK
[ERROR] Unable to retrieve logs output.
[ERROR] Log record: {"error":{"code":13,"message":"Error streaming log","details":[]}}
```

**Comment by avinal** [comment]
I think Sayan has explained this: https://github.com/openshift-pipelines/pipeline-service/pull/696#issuecomment-1609841786

**Comment by Roming22** [comment]
I believe the PR needs a rebase to pass CI

**Review by Roming22 — APPROVED** [review]
Can be merged as soon as all tests are green.

**Comment by ramessesii2** [comment]
A different reason:
```
task tests-downgrade has the status "Failed":

OK
[ERROR] Unable to retrieve logs output.
[ERROR] Log record: {"error":{"code":13,"message":"Error streaming log","details":[]}}
```

**Comment by ramessesii2** [comment]
This is what I see this time:
```
task tests-downgrade has the status "Failed":

OK
[ERROR] Unable to retrieve logs output.
[ERROR] Log record: {"error":{"code":13,"message":"Error streaming log","details":[]}}
```

I'm gonna rerun it for now and test it locally tomorrow if it fails again. Although, the reason seems unrelated but I'll confirm again.

**Comment by ramessesii2** [comment]
> should we have @ramessesii2 create a infra-deployments test PR against a pipeline-service branch with these changes

Sure @gabemontero, that sounds like the right thing to do. Although I'd like to clarify that if it's dependable on the CI? Meaning if CI passes, we don't need to test against infra?

**Comment by gabemontero** [comment]
> > should we have @ramessesii2 create a infra-deployments test PR against a pipeline-service branch with these changes
> 
> Sure @gabemontero, that sounds like the right thing to do. Although I'd like to clarify that if it's dependable on the CI? Meaning if CI passes, we don't need to test against infra? But yeah, CI will probably fail (53m already for `pipeline-service-upgrade-test`) Ah! may be you asked it w.r.t 1.11 bump.

@ramessesii2 I mean run the infra-deployments test regardless of whether this repo's CI passes or not

But yes, if say the infra-deployments test shows that our sync-waves change here has some unexpected negative effect, then catching it *BEFORE* we merge this PR will remove potential churn wrt getting the 1.11 stuff through

**Comment by ramessesii2** [comment]
Have raised a PR to test against infra-CI - https://github.com/redhat-appstudio/infra-deployments/pull/2153

**Review by gabemontero — APPROVED** [review]
ok we have a green RHTAP e2e over in https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/redhat-appstudio_infra-deployments/2153/pull-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-tests/1683856686500024320

per earlier from @sayan-biswas by way of @avinal the results failure on the downgrade portion of the upgrade test is believed to be a timing issue related to pruning

Assuming all that track I'm good merging @ramessesii2 .

**Pull request merged**
