### PR TITLE
Remove PaC config

### PR DESCRIPTION
**Pull request by enarha**
We now deploy PaC through the OSP operator, so the configuration is read from the TektonConfig CR.
https://pipelinesascode.com/docs/install/operator_installation/ The TektonConfig changes will be added to infra-deployments as we have different configs for staging and prod.

### CODE REVIEW

**Review by ramessesii2 — APPROVED** [review]

**Comment by ramessesii2** [comment]
Sorry, I didn't get which infra-deployment changes you meant. Is a future PR to infra-deployment is expected?

I've been looking at these - https://github.com/redhat-appstudio/infra-deployments/blob/main/components/pipeline-service/production/base/kustomization.yaml#L27 & https://github.com/redhat-appstudio/infra-deployments/blob/main/components/pipeline-service/staging/base/kustomization.yaml#L23 w.r.t the changes in this PR.

**Comment by enarha** [comment]
Yes. I expected those to fail. I'll submit a PR to fix those tomorrow.

**Comment by gabemontero** [comment]
OK I see that https://github.com/redhat-appstudio/infra-deployments/pull/2280 has merged @enarha but I forgot to ask during standup this morning ... is your testing effort from https://redhat-internal.slack.com/archives/C032EJ007C0/p1692626320815129 related to this item at all?

Or is this safe to merge from you point of view ?

**Comment by enarha** [comment]
@gabemontero No. I would like to update prod as well before we merge this as this specific configuration is used by both stage and prod. I shouldn't have opened this PR prematurely.

**Review by Roming22 — APPROVED** [review]

**Comment by Roming22** [comment]
@enarha Remove the `WIP` flag I added in the description once this PR is ready to be worked on again.

**Review by Roming22 — APPROVED** [review]

**Pull request merged**
