### PR TITLE
DO-NOT-MERGE: upgrade to openshift-pipelines 1.11; have openshift-pipelines install PaC

### PR DESCRIPTION
**Pull request by gabemontero**
We've tried this a few times now, but with my local reproducer, I've confirmed that 1.11 tekton controller (0.47.x  vs. 0.44.x for 1.10), fixes https://issues.redhat.com/browse/SRVKP-3131 , where as 1.10.4 does not, so an extra motivation to retry the leap to 1.11

Also had to do the additional step of having openshift-pipelines install PaC, as the 0.16 PaC yaml does not install the 1.11 PaC image correctly.

It gets the error 
```
{"severity":"EMERGENCY","timestamp":"2023-06-20T17:24:16.183286264Z","logger":"pipelinesascode","caller":"v2/main.go:239","message":"Failed to start configuration manager","error":"configmap \"config-logging\" not found","stacktrace":"knative.dev/eventing/pkg/adapter/v2.MainWithInformers\n\t/go/src/github.com/openshift-pipelines/pipelines-as-code/vendor/knative.dev/eventing/pkg/adapter/v2/main.go:239\nknative.dev/eventing/pkg/adapter/v2.MainWithEnv\n\t/go/src/github.com/openshift-pipelines/pipelines-as-code/vendor/knative.dev/eventing/pkg/adapter/v2/main.go:158\nknative.dev/eventing/pkg/adapter/v2.MainWithContext\n\t/go/src/github.com/openshift-pipelines/pipelines-as-code/vendor/knative.dev/eventing/pkg/adapter/v2/main.go:133\nmain.main\n\t/go/src/github.com/openshift-pipelines/pipelines-as-code/cmd/pipelines-as-code-controller/main.go:46\nruntime.main\n\t/usr/lib/golang/src/runtime/proc.go:250"}
```

If for some reason this does not hold water in RHTAP e2e's, I'll revert that and portion of the change, and use the 0.19 version of the upstream yaml.

Conversely, as our current manual deploy of tekton-chains via upstream yaml still works with 1.11, I left that alone and just bumped the image replacement.  I say we minimize the change there for now, and address that in a subsequent PR.

### CODE REVIEW

**Comment by gabemontero** [comment]
rosa failure on the upgrade test

/retest

**Comment by Roming22** [comment]
@gabemontero Upgrade test is failing on the metrics test post-upgrade with:
`Error from server (InternalError): error when creating "/workspace/source/operator/test/manifests/test/metrics/curl-metrics-service-pipeline.yaml": Internal error occurred: failed calling webhook "webhook.pipeline.tekton.dev": failed to call webhook: Post "https://tekton-pipelines-webhook.openshift-pipelines.svc:443/defaulting?timeout=10s": service "tekton-pipelines-webhook" not found`

**Comment by gabemontero** [comment]
> @gabemontero Upgrade test is failing on the metrics test post-upgrade with: `Error from server (InternalError): error when creating "/workspace/source/operator/test/manifests/test/metrics/curl-metrics-service-pipeline.yaml": Internal error occurred: failed calling webhook "webhook.pipeline.tekton.dev": failed to call webhook: Post "https://tekton-pipelines-webhook.openshift-pipelines.svc:443/defaulting?timeout=10s": service "tekton-pipelines-webhook" not found`

yeah I asked you about that in slack :-) ..... I think that means the 1.11 uninstall is not totally clean, and the webhook it is adding is not fully removed

**Comment by gabemontero** [comment]
also, per slack conversations, we have 2 chains controllers running, and there is not quick disable field like with PaC

need to take on having the operator deploy chains

**Comment by gabemontero** [comment]
I think at this point we go with @Roming22 's https://github.com/openshift-pipelines/pipeline-service/pull/688

**Pull request closed without merging**
