### PR TITLE
Update kustomization files to latest standard

### PR DESCRIPTION
**Pull request by Roming22**
This removes deprecation warning when applying kustomize to the files

### CODE REVIEW

**Comment by gabemontero** [comment]
were you able to confirm the deprecation warnings were gone before the pipelineruns got pruned @Roming22 ?

otherwise, 
/lgtm

**Comment by Roming22** [comment]
@gabemontero There are some warning left because they come from tekton-results resources. I've submitted a change for that.

I ran `kustomize build` locally, I didn't look at the logs, as there's no reason it should behave differently.

**Pull request merged**
