### PR TITLE
PLNSRVCE-1154: Move CI to StoneSoup Prod MVP

### PR DESCRIPTION
**Pull request by xinredhat**
As PR https://github.com/redhat-appstudio/infra-deployments/pull/2012 is merged, we can enable CI to load secrets as environment variables in Pipeilnes.

### CODE REVIEW

**Comment by gabemontero** [comment]
The pipeline-service-test passing on RHTAP prod is a great sign @xinredhat :-) 

The upgrade deploy cluster logs were unavailable when I looked just now.

Let's see if a retest gets them, or if things are broke enough, that they are unavailable to start with.

**Comment by gabemontero** [comment]
ok this time the deploy cluster worked, but the setup ci running failed

here are the full logs @xinredhat if they are pruned by the time you log back in:

```
step-create-ci-runner-container
+ kubectl -n openshift-config get secret/pull-secret -o yaml
+ yq -i '.metadata.namespace="default" |
    del(.type) | 
    del(.metadata.uid) | 
    del(.metadata.resourceVersion) | 
    .data.["auth.json"]=.data.[".dockerconfigjson"] | 
    del(.data.[".dockerconfigjson"])' /tmp/pull-secret.yaml
+ kubectl -n default apply -f /tmp/pull-secret.yaml
secret/pull-secret created
+++ dirname /workspace/source/ci/images/ci-runner/hack/bin/create-ci-runner-container.sh
++ cd /workspace/source/ci/images/ci-runner/hack/bin/../manifests
++ pwd
+ MANIFEST_DIR=/workspace/source/ci/images/ci-runner/hack/manifests
+ kubectl -n default apply -k /workspace/source/ci/images/ci-runner/hack/manifests/sidecar
persistentvolumeclaim/ci-runner-pvc created
Warning: would violate PodSecurity "restricted:latest": privileged (container "ci-runner" must not set securityContext.privileged=true), allowPrivilegeEscalation != false (container "ci-runner" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "ci-runner" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "ci-runner" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "ci-runner" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
pod/ci-runner created
+ kubectl -n default wait pod/ci-runner --for=condition=Ready --timeout=90s
error: timed out waiting for the condition on pods/ci-runner

step-copy-plnsvc-code
2023/06/26 17:07:07 Skipping step because a previous step failed
```

doesn't look like the script dumps the ci-runner pods logs/events on failure

either add that, or use Romain's don't delete the test cluster option

**Comment by xinredhat** [comment]
> The pipeline-service-test passing on RHTAP prod is a great sign @xinredhat :-)
> 
> The upgrade deploy cluster logs were unavailable when I looked just now.
> 
> Let's see if a retest gets them, or if things are broke enough, that they are unavailable to start with.

@gabemontero the pipeline-service-upgrade-test  failure is expected, it's not caused by this PR change. It failed at downgrade deploy. I will investigate why it failed at downgrade deploy. Because the baseline deploy passed, the downgrade deploy should be passed as well.

**Comment by xinredhat** [comment]
Here is the upgrade deploy cluster logs 
```
Started to destroy cluster [ci-865be050f6]...
+ echo 'Started to destroy cluster [ci-865be050f6]...'
+ open_bitwarden_session
+ setx_off
+ set +x
Error: BW_CLIENTID is unset.
```

**Comment by xinredhat** [comment]
> Here is the upgrade deploy cluster logs
> 
> ```
> Started to destroy cluster [ci-865be050f6]...
> + echo 'Started to destroy cluster [ci-865be050f6]...'
> + open_bitwarden_session
> + setx_off
> + set +x
> Error: BW_CLIENTID is unset.
> ```

@gabemontero yes, the failure is expected, because [destroy-cluster](https://github.com/openshift-pipelines/pipeline-service/blob/8ad0ac1a82e2166ce8cbd826b5047e9c01718131/.tekton/tasks/destroy-cluster.yaml#L21-L35) task doesn't have the variable **BW_CLIENTID**  in the PR

**Comment by xinredhat** [comment]
@gabemontero could you review it? please merger it if it looks good to you.

**Comment by gabemontero** [comment]
can you explain to me how the `BW_CLIENTID` issue is to be resolved @xinredhat ?  

if it is explained elsewhere apologies but I have missed it

**Comment by xinredhat** [comment]
@gabemontero the BW_CLIENTID issue cannot be resolved. The reason is that it doesn't pass BW_CLIENTID as parameter in task [destroy-cluster](https://github.com/openshift-pipelines/pipeline-service/blob/8ad0ac1a82e2166ce8cbd826b5047e9c01718131/.tekton/tasks/destroy-cluster.yaml#L21-L35) in this PR. As this failure occured at downgrade phase, the task cloned repo from main branch instead of the PR. [destroy-cluster.sh](https://github.com/openshift-pipelines/pipeline-service/blob/main/ci/images/ci-runner/hack/bin/destroy-cluster.sh) cannot find `BW_CLIENTID` variable while calling [open_bitwarden_session](https://github.com/openshift-pipelines/pipeline-service/blob/main/ci/images/ci-runner/hack/bin/destroy-cluster.sh#L39) function . That's why it reported the failure, which means the BW_CLIENTID error is expected.

**Comment by gabemontero** [comment]
> @gabemontero the BW_CLIENTID issue cannot be resolved. The reason is that it doesn't pass BW_CLIENTID as parameter in task [destroy-cluster](https://github.com/openshift-pipelines/pipeline-service/blob/8ad0ac1a82e2166ce8cbd826b5047e9c01718131/.tekton/tasks/destroy-cluster.yaml#L21-L35) in this PR. As this failure occured at downgrade phase, the task cloned repo from main branch instead of the PR. [destroy-cluster.sh](https://github.com/openshift-pipelines/pipeline-service/blob/main/ci/images/ci-runner/hack/bin/destroy-cluster.sh) cannot find `BW_CLIENTID` variable while calling [open_bitwarden_session](https://github.com/openshift-pipelines/pipeline-service/blob/main/ci/images/ci-runner/hack/bin/destroy-cluster.sh#L39) function . That's why it reported the failure, which means the BW_CLIENTID error is expected.

OK ..... so obviously we can't live with a long term failure.

But if I interpret what you are saying then, is it that once your PR merges here, and your changes are in place, the next PR that comes in will have your change in the main branch, and then the downgrade path will have the necessary parameters to still work.

Do I have that correct @xinredhat ?

If so, then yes, I think this is OK to merge.  But I'd like to cross reference with the rest of the team, ideally in stand up / scrum, so everyone including @adambkaplan and @Roming22 understand.

thanks.

**Comment by xinredhat** [comment]
> Do I have that correct @xinredhat ?

@gabemontero Correct.

**Comment by gabemontero** [comment]
OK good thanks @xinredhat 

Couple of things
- changed the PR title to ref the story vs. the epic
- moved that story into the current sprint 241
- I will mention in planning, then merge

**Comment by gabemontero** [comment]
Per planning merging this

Please pay attention @xinredhat to how the downgrade jobs perform after your PR here is merged.

**Pull request merged**
