### PR TITLE
Fix TektonConfig

### PR DESCRIPTION
**Pull request by Roming22**
Restore a setting that was mistakenly removed with commit b2626be4fc649b5184b8bf3e661bbc46319c884b
which break the deployment of the application

### CODE REVIEW

**Comment by gabemontero** [comment]
Interestingly, there is no godoc for that profile field @Roming22 @enarha :  https://github.com/tektoncd/operator/blob/main/pkg/apis/operator/v1alpha1/tektonconfig_types.go#L77

the default does appear to be basic - https://github.com/tektoncd/operator/blob/main/pkg/apis/operator/v1alpha1/tektonconfig_defaults.go#L28

searching for refs in the operator code, I see hits to v1alpha1 addons and the tekton dashboard

my "guess" is this could be intentional, as we need neither of those, but I agree @Roming22 should officially declare that as the original commit did not touch upon that as well

**Comment by enarha** [comment]
So we are actually changing `all` to `basic` by removing that field. The documentation touches on that https://tekton.dev/docs/operator/tektonconfig/#profile

**Comment by Roming22** [comment]
@enarha Thanks for catching that! Fixed.

**Pull request merged**
