### PR TITLE
Migrator config patches

### PR DESCRIPTION
**Pull request by sayan-biswas**
Add patches to migrator database config to transform DB secret key values.

Causing error in pod creation:
container "migrator" in pod "tekton-results-api-5fd5f67554-4vkvz" is waiting to start: CreateContainerConfigError

### CODE REVIEW

**Review by adambkaplan — COMMENTED** [review]
/ok-to-test

**Review by adambkaplan — APPROVED** [review]
/lgtm

These patches align with https://github.com/openshift-pipelines/pipeline-service/blob/main/operator/gitops/argocd/pipeline-service/tekton-results/base/api-db-config.yaml

**Review by avinal — APPROVED** [review]
Loogs good

**Review by Roming22 — APPROVED** [review]

**Pull request merged**
