### PR TITLE
refactor: Create 'ci' folder

### PR DESCRIPTION
**Pull request by Roming22**
This commit is part of a larger set of commits with the goal of restructuring the repository.

Signed-off-by: Romain Arnaud <rarnaud@redhat.com>

### CODE REVIEW

**Comment by Roming22** [comment]
I've asked Xin to remove the prow tests, as it is my understanding that they are redundant with `Pipelines as Code CI / pipeline-service-static-code-analysis`.

Since `pipeline-service-static-code-analysis` is green, I assume that the PR content is OK.

**Comment by Roming22** [comment]
@xinredhat Tests should pass once https://github.com/openshift/release/pull/33405 is merged.

**Comment by Roming22** [comment]
> the PR [openshift/release#33194](https://github.com/openshift/release/pull/33194) is ready for it.
PR has been merged, yet the tests still appear in the CI report. Do we need to do something else?

**Review by bnallapeta — APPROVED** [review]
Overall looks good. If any links are broken or paths needs to be updated, we could raise subsequent PRs.

**Pull request merged**
