### PR TITLE
Reapply "remove tekton results migrator"

### PR DESCRIPTION
**Pull request by enarha**
This reverts commit dfb5828501e9ec7b2027d37db4e16f8748091bd8.

This reintroduces the "remove tekton results migrator" change. Since it's dependant on the migrator confuguration in the results fork now removed, readding the change in pipeline service, broke the main branch. This will fix the main branch.

This takes the ref to the results fork one commit further (a602fb3e858f6a3195374d2175053db7e5db9f77) than the commit used in prod (1c5b3054ffb52f172fda31587d7dfd88a9724c8f), but it's a change that does not affect the Results service.

### CODE REVIEW

**Comment by enarha** [comment]
I was able to verify the fix manually (deploy + running the test.sh).

**Review by gabemontero — APPROVED** [review]
merge whenever you are ready @enarha

**Comment by ramessesii2** [comment]
tests are failing, for ref:-
```
test-pipeline-service-upgrade-ocp-414

Failure snippet:
task test-downgrade has the status "Failed":

from server for: "/workspace/source/operator/test/manifests/setup/pipeline-service": rolebindings.rbac.authorization.k8s.io "appstudio-pipelines-runner-rolebinding" is forbidden: User "system:serviceaccount:default:default" cannot get resource "rolebindings" in API group "rbac.authorization.k8s.io" in the namespace "plnsvc-tests"
command terminated with exit code 1
+ exit 1
```

```
test-pipeline-service-deployment-ocp-414
Failure snippet:
task test-pipeline-service has the status "Failed":

ensure CRDs are installed first
command terminated with exit code 1
+ exit 1
```

**Comment by ramessesii2** [comment]
ohh I just saw your comment Emil that the tests are expected to fail.

**Comment by avinal** [comment]
Yeah I was just going to point out that.

**Review by avinal — APPROVED** [review]
Good to go

**Pull request merged**
