### PR TITLE
PLNSRVCE-1467: fix missing datasorce error in stage/prod pipeline-service grafana dashboard

### PR DESCRIPTION
**Pull request by gabemontero**
In comparing with other RHTAP components whose grafana dashboards were working, none of them had the datasource/uid pattern in their JSON in the repos.  However, when I examined their JSON live, I saw example of this.

I suspect that when the last update to our dashboard was made, it pulled in live data like this datasource/uid pairing, and what we had was now stale.

Here is a screen shot of a RHTAP bootstrap against my local cluster using my pipeline service branch for this PR:

fix-grafana-screen-shot

@Roming22 @enarha @avinal @sayan-biswas @ramessesii2 @prietyc123 FYI since all of you along with me have touched this dashboard at one time or another.

### CODE REVIEW

**Review by Roming22 — APPROVED** [review]

**Comment by gabemontero** [comment]
Also a manual tweek to the one of our live staging dashboards, removing some of those datasource/uid entries, seemed to help with the panel or two I edited manually.

**Comment by Roming22** [comment]
@gabemontero I've opened #785 to prevent the issue from happening again.

**Pull request merged**
