### PR TITLE
Optimizing the process of ROSA provisioning in CI

### PR DESCRIPTION
**Pull request by xinredhat**

### CODE REVIEW

**Comment by xinredhat** [comment]
This PR is ready for review. it can save around 8 mins comparing to before.

**Comment by xinredhat** [comment]
hold on, need to investigate the following error 
```
+ argocd login openshift-gitops-server-openshift-gitops.apps.rosa.ci-c629285c6d.j694.p3.openshiftapps.com --grpc-web --insecure --username admin --password GdWP1AB3o4E8VKDMcYSfqHFJNeQpksw2
time="2023-10-17T03:43:19Z" level=fatal msg="context deadline exceeded"
command terminated with exit code 20
```

**Comment by xinredhat** [comment]
Pipeline Service failed due to the following error
```
        Message:      one or more objects failed to apply, reason: namespaces "openshift-pipelines" not found,admission webhook "validation.webhook.operator.tekton.dev" denied the request: validation failed: missing field(s): spec.targetNamespace. 
```

**Comment by xinredhat** [comment]
Sometimes task `deploy-pipeline-service` failed due to pipeline-service  application taking more than 14 mins to reach Synced status

**Review by Roming22 — APPROVED** [review]

**Pull request merged**
