### PR TITLE
update tekton-results env and sha reference

### PR DESCRIPTION
**Pull request by avinal**
- sync the config.env with the upstream version
- update the tekton results reference

Signed-off-by: Avinal Kumar <avinal@redhat.com>

### CODE REVIEW

**Comment by ramessesii2** [comment]
@avinal I rebased this branch and seem to have added me to the contributors in the commit. I didn't expect that. Please force push rebasing.

**Comment by avinal** [comment]
I think #948 is required to pass the tests.

**Comment by gabemontero** [comment]
@openshift-pipelines/pipelines-service a new flake in the downgrade portion of the upgrade test I've never seen before:
```
Failure snippet:
task test-downgrade has the status "Failed":

from server for: "/workspace/source/operator/test/manifests/setup/pipeline-service": rolebindings.rbac.authorization.k8s.io "appstudio-pipelines-runner-rolebinding" is forbidden: User "system:serviceaccount:default:default" cannot get resource "rolebindings" in API group "rbac.authorization.k8s.io" in the namespace "plnsvc-tests"
command terminated with exit code 1
+ exit 1
```

**Comment by gabemontero** [comment]
deploy cluster flake on the vanilla ocp-414 test:
`TaskRun "test-pipeline-service-deployment-ocp-414-qr7qz-deploy-cluster" failed to finish within "1h0m0s"`

**Comment by gabemontero** [comment]
no flakes this time tests green ... merging

**Pull request merged**
