### PR TITLE
[WIP] Update tekton results manifests

### PR DESCRIPTION
**Pull request by avinal**
- reference tekton results manifests from downstream repo
  openshift-pipelines/tektoncd-results
- update variable name for database secret and form literals
- expose rest endpoint and remove grpc
- remove initcontainer script from results api deployments

Signed-off-by: Avinal Kumar <avinal@redhat.com>

### CODE REVIEW

**Comment by avinal** [comment]
I have removed the initcontainer script wrt to [this](https://github.com/openshift-pipelines/pipeline-service/pull/468#discussion_r1100544049) discussion but the code should migrate somewhere, I am not sure where.

**Comment by Mo3m3n** [comment]
@avinal if you have removed the db deployment manifests without moving that somewhere else, it is not going to work.
You need a db for results to work.

**Comment by Roming22** [comment]
@avinal You'll need to rebase.

**Comment by Roming22** [comment]
@avinal When the PR is ready for review, please clean up the commit history and remove `[WIP]` from the PR title.

**Comment by avinal** [comment]
Closing in favor of #504

**Pull request closed without merging**
