### PR TITLE
Use the beta by default in OpenShift Pipelines

### PR DESCRIPTION
**Pull request by Roming22**

### CODE REVIEW

**Comment by Roming22** [comment]
I can see the following error in the operator's pod logs:

```
{"level":"error","logger":"tekton-operator-lifecycle","caller":"controller/controller.go:566","msg":"Reconcile error","commit":"1d0fb8d","knative.dev/pod":"openshift-pipelines-operator-5bc7b9c965-r4tfb","knative.dev/controller":"github.com.tektoncd.operator.pkg.reconciler.shared.tektonconfig.Reconciler","knative.dev/kind":"operator.tekton.dev.TektonConfig","knative.dev/traceid":"039e1e02-3ba0-4b9b-b847-55b4c72dd2d3","knative.dev/key":"config","duration":0.046486388,"error":"failed to set finalizers: admission webhook \"validation.webhook.operator.tekton.dev\" denied the request: validation failed: invalid value: beta: spec.pipeline.enable-api-fields","stacktrace":"knative.dev/pkg/controller.(*Impl).handleErr\n\t/go/src/github.com/tektoncd/operator/vendor/knative.dev/pkg/controller/controller.go:566\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\t/go/src/github.com/tektoncd/operator/vendor/knative.dev/pkg/controller/controller.go:543\nknative.dev/pkg/controller.(*Impl).RunContext.func3\n\t/go/src/github.com/tektoncd/operator/vendor/knative.dev/pkg/controller/controller.go:491"} 
```

I thought I followed [the doc|https://tekton.dev/docs/pipelines/additional-configs/#beta-features]. Looking into the problem.

**Comment by adambkaplan** [comment]
Let's be careful about what "beta" means here - @vdemeester I think this might be a source of confusion for teams migrating to the v1 API. I don't think this means "enable the v1beta1 API" - that is still there and isn't going away. That API version, however, _might_ have breaking changes from 1.9 to 1.10...

**Pull request merged**
