### PR TITLE
PLNSRVCE-1307: add get crds, wach pipelineruns, to exporter rbac

### PR DESCRIPTION
**Pull request by gabemontero**
Needed for https://github.com/openshift-pipelines/pipeline-service-exporter/pull/23 changes

### CODE REVIEW

**Comment by gabemontero** [comment]
destroy cluster flaked

/retest pipeline-service-test

**Comment by Roming22** [comment]
Adding a FREEZE header to the PR. I'd prefer to make sure we can deliver the downstream images and the RHTAP-872 story before we merge anything else.

That's of course open to discussion if any one feels that is not the right move.

**Comment by gabemontero** [comment]
Looks like I accidentally closed this

Still needed for https://github.com/openshift-pipelines/pipeline-service-exporter/pull/23

**Comment by gabemontero** [comment]
also wondering if we can unfreeze this @Roming22 given 872 is in and we've scaled down the exporter in RHTAP until the exporter rework like this is completed?

**Review by Roming22 — APPROVED** [review]

**Pull request merged**
