### PR TITLE
Always register clusters to KCP

### PR DESCRIPTION
**Pull request by Roming22**
Current behavior generates the following issues:
- An upgrade of the KCP version will not deploy existing syncers.
- KCP syncers can have different version for each cluster, which breaks
  consistency.
- If the creation of the syncer on the compute cluster fails for any reason,
  the syncer will not be deployed on the next run as it is already declared
  in the KCP workspace.

Proposed behavior generates the following issues:
- An upgrade of the KCP version will deploy on all clusters, which may trigger
  an interruption of service if there is an issue with the syncer.
- The team operating the KCP workspace into which the clusters are registered
  cannot customize the configuration of the syncer, as it would get overwritten
  at every run.

Signed-off-by: Romain Arnaud <rarnaud@redhat.com>

### CODE REVIEW

**Comment by fgiloux** [comment]
At a design level I am not for the change for the reasons previously explained:
- more operational knowledge than what is offered by GitOps/Argo CD may be needed for component lifecycle management
  - to avoid continuous disruptions
  - to avoid "magical" things happening by triggers unknown to the users
  - to cleanly manage upgrades and like
  
At a practical level I tried to run the sync command twice and the result was:
`error: failed to create WorkloadCluster: workloadclusters.workload.kcp.dev "api-crc-testing" already exists`

**Comment by bnallapeta** [comment]
I believe this is an important PR as it drives us to define the expectations of Pipeline Service on certain things. Thanks @Roming22 for raising it.

I think we need to maintain the consistency between the kcp stable versions and kcp syncer image. And to address the issues mentioned by @fgiloux, we need to test when a new version is released. Perhaps, in the future, this will be a CI that will be triggered with each upgrade which checks e2e functionality. But until we get there, we would need to do it manually. Because, the alternative to this is a mismatch between kcp stable and syncer image which should not be the case.

**Comment by fgiloux** [comment]
> I think we need to maintain the consistency between the kcp stable versions and kcp syncer image. 

From an operation point of view it won't be possible to have consistency at all time. During an upgrade, the control plane  will be upgraded first, workload clusters, i.e syncers later in a rolling manner. For some period of time versions won't be aligned. This is very similar to what happens between Kubernetes control plane and kubelet versions. [Compatibility](https://kubernetes.io/releases/version-skew-policy/#kubelet) is ensured at n-2 so that the cluster stays functional. This is currently not the case with kcp/syncer but will eventually be. Nevertheless we should aim to limit version skew to what is strictly necessary.

I do agree to what @bnallapeta wrote:
- we need testing/validation for each kcp version bump (and we added this item to our sprint for release-0.5)
- ideally this would be supported by a CI workflow

**Comment by Roming22** [comment]
@bnallapeta @ramessesii2 @Mo3m3n PR ready for review.

The PR can be tested with:
```
./images/kcp-registrar/register.sh --kcp-org root:default --kcp-workspace pipeline-service-compute --kcp-sync-tag v0.8.0 --workspace-dir $WORK_DIR
./images/kcp-registrar/register.sh --kcp-org root:default --kcp-workspace pipeline-service-compute --kcp-sync-tag v0.8.2 --workspace-dir $WORK_DIR
```
and checking the version of the kcp-syncer image in between the calls.

**Review by bnallapeta — APPROVED** [review]
LGTM. Verified it.

FYI: What's funny is that the existing logic was not working anymore. Because the 'if condition' where we were checking if the cluster name exists in the synctarget name is changed by kcp. It does not display the cluster name anymore. So in a way, if was always failing and else was executed which is want this PR is doing :)

**Comment by bnallapeta** [comment]
```
[bnr@bnr pipelines-service]$ ./images/kcp-registrar/register.sh --kcp-org root:default --kcp-workspace pipeline-service-compute --kcp-sync-tag v0.8.2 --workspace-dir /tmp/tmp.3L7vDNpAvp/
Workspace: root:default:pipeline-service-compute
Registering clusters to kcp
Getting the list of registered clusters
Processing cluster api-ci-ln-x5c6ghb-76ef8-origin-ci-int-aws-dev-rhcloud-com (1/1)
Registering cluster
Synctarget "4d9ca4ba136a227d71855d82743b7c80" already exists.
Updating service account "kcp-syncer-4d9ca4ba136a227d71855d82743b7c80-1aatv34i".
Updating cluster role "kcp-syncer-4d9ca4ba136a227d71855d82743b7c80-1aatv34i" with

 1. write and sync access to the synctarget "kcp-syncer-4d9ca4ba136a227d71855d82743b7c80-1aatv34i"
 2. write access to apiresourceimports.

Creating or updating cluster role binding "kcp-syncer-4d9ca4ba136a227d71855d82743b7c80-1aatv34i" to bind service account "kcp-syncer-4d9ca4ba136a227d71855d82743b7c80-1aatv34i" to cluster role "kcp-syncer-4d9ca4ba136a227d71855d82743b7c80-1aatv34i".

Wrote physical cluster manifest to /tmp/syncer-api-ci-ln-x5c6ghb-76ef8-origin-ci-int-aws-dev-rhcloud-com.yaml for namespace "kcp-syncer-4d9ca4ba136a227d71855d82743b7c80-1aatv34i". Use

  KUBECONFIG=<pcluster-config> kubectl apply -f "/tmp/syncer-api-ci-ln-x5c6ghb-76ef8-origin-ci-int-aws-dev-rhcloud-com.yaml"

to apply it. Use

  KUBECONFIG=<pcluster-config> kubectl get deployment -n "kcp-syncer-4d9ca4ba136a227d71855d82743b7c80-1aatv34i" kcp-syncer-4d9ca4ba136a227d71855d82743b7c80-1aatv34i

to verify the syncer pod is running.
namespace/kcp-syncer-4d9ca4ba136a227d71855d82743b7c80-1aatv34i unchanged
serviceaccount/kcp-syncer-4d9ca4ba136a227d71855d82743b7c80-1aatv34i unchanged
secret/kcp-syncer-4d9ca4ba136a227d71855d82743b7c80-1aatv34i-token unchanged
clusterrole.rbac.authorization.k8s.io/kcp-syncer-4d9ca4ba136a227d71855d82743b7c80-1aatv34i unchanged
clusterrolebinding.rbac.authorization.k8s.io/kcp-syncer-4d9ca4ba136a227d71855d82743b7c80-1aatv34i unchanged
**secret/kcp-syncer-4d9ca4ba136a227d71855d82743b7c80-1aatv34i configured
deployment.apps/kcp-syncer-4d9ca4ba136a227d71855d82743b7c80-1aatv34i configured**
Configuring KCP workspace
clusterrole.rbac.authorization.k8s.io/apibinding:kubernetes unchanged
clusterrolebinding.rbac.authorization.k8s.io/apibinding:kubernetes:all-users unchanged

```

Changed 
from:
```
[bnr@bnr pipelines-service]$ k -n kcp-syncer-4d9ca4ba136a227d71855d82743b7c80-1aatv34i describe pod/kcp-syncer-4d9ca4ba136a227d71855d82743b7c80-1aatv34i-79b85bzxmd | grep -i Image:
    Image:         ghcr.io/kcp-dev/kcp/syncer:v0.8.0
```

to:
```
[bnr@bnr pipelines-service]$ k -n kcp-syncer-4d9ca4ba136a227d71855d82743b7c80-1aatv34i describe pod/kcp-syncer-4d9ca4ba136a227d71855d82743b7c80-1aatv34i-d9d889t7nq | grep -i Image:
    Image:         ghcr.io/kcp-dev/kcp/syncer:v0.8.2

```

**Pull request merged**
