### PR TITLE
Refactor update-dependencies 2/2

### PR DESCRIPTION
**Pull request by Roming22**
* Use the existing GitHubApp to manage changes to the repository
* Try to the make the task generic enough so it can be submitted to redhat-appstudio/build-definitions

### CODE REVIEW

**Comment by Roming22** [comment]
I ran a test by having the pipeline run on a pull_request, and ended up with #746.
So I believe it works (at least well enough that we can fix bugs in a future PR).

**Review by sayan-biswas — APPROVED** [review]

**Pull request merged**
