### PR TITLE
Use tekton.dev/v1 in pipelines/tasks

### PR DESCRIPTION
**Pull request by Roming22**
rh-pre-commit.version: 2.1.0
rh-pre-commit.check-secrets: ENABLED

### CODE REVIEW

**Comment by Roming22** [comment]
Tests are failing with:
```
++ kubectl create -f /workspace/source/operator/test/manifests/test/tekton-chains/public-key.yaml -n plnsvc-tests
++ cut '-d ' -f1
Error from server (BadRequest): error when creating "/workspace/source/operator/test/manifests/test/tekton-chains/public-key.yaml": admission webhook "webhook.pipeline.tekton.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "serviceAccountName"
+ pipeline_name=
command terminated with exit code 1
```

**Review by enarha — COMMENTED** [review]
/lgtm

**Comment by Roming22** [comment]
Test failing with:
```
  - Run pipeline: ++ basename quay.io/aptible/alpine:latest
+ image_name=alpine:latest
+ image_dst=image-registry.openshift-image-registry.svc:5000/plnsvc-tests/alpine:latest
++ tkn -n plnsvc-tests pipeline start simple-copy --param image-src=quay.io/aptible/alpine:latest --param image-dst=image-registry.openshift-image-registry.svc:5000/plnsvc-tests/alpine:latest --serviceaccount chains-test --workspace name=shared,pvc,claimName=tekton-build
++ head -1
++ sed 's:.* ::'
+ pipeline_name=simple-copy-run-56ddc
command terminated with exit code 141
```

**Comment by Roming22** [comment]
/test test-pipeline-service-upgrade-ocp-414

downgrade-pipeline-service did not complete

**Comment by Roming22** [comment]
CI is finally green, merging.

**Pull request merged**
