### PR TITLE
Upgrade to OSP 1.12

### PR DESCRIPTION
**Pull request by Roming22**

### CODE REVIEW

**Comment by enarha** [comment]
/lgtm
Do you know what min version of OCP is required for OSP 1.12?

**Comment by enarha** [comment]
Nevermind. I found it "Before upgrading to the Red Hat OpenShift Pipelines Operator 1.12, ensure that you have at least installed the OpenShift Container Platform 4.12.19 or 4.13.1 version on your cluster."

**Review by gabemontero — COMMENTED** [review]
I'll reiterate what I mentioned in slack @Roming22 

I think we need to continue the practice of creating a test PR in infra deployments that points to a pipeline-service branch that has this change, and see how the fully e2e suite looks.

**Comment by gabemontero** [comment]
> Nevermind. I found it "Before upgrading to the Red Hat OpenShift Pipelines Operator 1.12, ensure that you have at least installed the OpenShift Container Platform 4.12.19 or 4.13.1 version on your cluster."

good catch @enarha  .... and stage/prod are beyond 4.12.19, so we should be good there

**Comment by Roming22** [comment]
PR to test in RHTAP: https://github.com/redhat-appstudio/infra-deployments/pull/2507

**Comment by gabemontero** [comment]
there may be a consistently occurring chains/verify-enterprise-contract e2e failure occurring with 1.12 ... see https://github.com/redhat-appstudio/infra-deployments/pull/2507#issuecomment-1747406372

**Comment by Roming22** [comment]
https://github.com/redhat-appstudio/infra-deployments/pull/2507 is now green. Merging the change.

**Pull request merged**
