### PR TITLE
Update OWNERS

### PR DESCRIPTION
**Pull request by Roming22**

### CODE REVIEW

**Comment by Roming22** [comment]
@xinredhat Please check why `pipeline-service-test` is failing. The failure is quite consistent.

**Comment by xinredhat** [comment]
@Roming22 the error is because cluster operator `monitoring` is not ready after waiting 10 mins. I opened a new [PR](https://github.com/openshift-pipelines/pipeline-service/pull/732/) for debugging the issue.

**Review by ramessesii2 — APPROVED** [review]

**Comment by ramessesii2** [comment]
Feel free to merge  @xinredhat 😺

**Pull request merged**
