### PR TITLE
tektoncd-results update

### PR DESCRIPTION
**Pull request by gabemontero**
replaces https://github.com/openshift-pipelines/pipeline-service/pull/590 since we had to add the migrator image to the replace images section

@sayan-biswas @adambkaplan @Roming22 FYI

### CODE REVIEW

**Review by adambkaplan — APPROVED** [review]
LGTM

:crossed_fingers: testing succeeds.

**Comment by xinredhat** [comment]
I am seeing the error
```
NAME                                      READY   STATUS                            RESTARTS         AGE
storage-pool-0-0                          1/1     Running                           0                33m
tekton-results-api-5fd5f67554-2b4v8       0/1     Init:CreateContainerConfigError   4                37m
tekton-results-database-0                 1/1     Running                           0                36m
tekton-results-watcher-7d67b79967-6c6nn   1/1     Running                           11 (5m16s ago)   37m
```
Logs in tekton-results-api pod:
```
2023/04/14 04:31:56 dialing tekton-results-api-service.tekton-results.svc.cluster.local:50051...
2023/04/14 04:32:26 did not connect: context deadline exceeded
```

**Comment by Roming22** [comment]
Replaced by #595

**Pull request closed without merging**
