### PR TITLE
Set pipeline enable-api-fields alpha

### PR DESCRIPTION
**Pull request by enarha**
Requested by users to allow use of StepSpecs.

### CODE REVIEW

**Comment by gabemontero** [comment]
are there any Jira's or slack threads for reference @enarha ?

Also, IMO @Roming22 this change deserves treatment similar to what we did with 1.11 where we created a test branch, then created a test PR off of infra-deployments to run the e2e's.

Would you agree @Roming22 ?

**Comment by enarha** [comment]
https://issues.redhat.com/browse/PLNSRVCE-1368. The Slack thread and few other Jiras are linked into this one.

**Comment by gabemontero** [comment]
> https://issues.redhat.com/browse/PLNSRVCE-1368. The Slack thread and few other Jiras are linked into this one.

thanks for the ref and memory refresh @enarha 

yeah given recent experiences I definitely think we minimally need to do the pre-merge infra-deployments test PR

probably wouldn't hurt to discuss in general ... in addition to the potential concerns you noted in the Jira, I *think* it is possible other features besides `StepSpecs` gets pulled in ... forget if there is a way to pick and choose which alpha features are pulled in.

@Roming22 @adambkaplan FYI

**Comment by enarha** [comment]
Alpha features are generally not supported. Workaround has been agreed upon. The feature will be available as beta in later version of OSP (probably 1.13).

**Pull request closed without merging**
