### PR TITLE
Update tekton results version and configuration

### PR DESCRIPTION
**Pull request by sayan-biswas**
Use new version of Tekton Results and update configuration to reflect on the upstream changes.

### CODE REVIEW

**Review by gabemontero — APPROVED** [review]
/lgtm

**Comment by Roming22** [comment]
@sayan-biswas Can you close #610 if this PR overrides it?

**Comment by gabemontero** [comment]
fyi @Roming22 we may have a perm fail in the upgrade tests 

if so, trying to diagnose in https://github.com/openshift-pipelines/pipeline-service/pull/619

**Comment by gabemontero** [comment]
> fyi @Roming22 we may have a perm fail in the upgrade tests
> 
> if so, trying to diagnose in #619

nevermind just saw the slack thread update around the flaky storage pool stateful set

**Comment by gabemontero** [comment]
new failure both here and in #619 in `test-post-upgrade`

**Comment by gabemontero** [comment]
/retest pipeline-service-test

see if we get lucky with known issues in test setup

**Comment by gabemontero** [comment]
ok no transient pod state checks yet, but have merged 
- only create the minio secret once merged 
- updates to the pod security tests which should address flakes seen so far (unless the pruner pod stays pops up, stays alive long enough, and has unexpected scc or host network)


let's see if that is enough to get clean tests 

/retest

**Comment by gabemontero** [comment]
@sayan-biswas forgot - you need to rebase this PR in order to pick up my recent fixes

you are still getting
```
[security]
 - Check security: 
  - Check Pod Security openshift-pipelines: 
Error from server (NotFound): pods "tekton-resource-pruner-k9pl9-28043776-p7jnm" not found
command terminated with exit code 123
``` 

but with https://github.com/gabemontero/pipeline-service/blob/eebf10d39510e047db95098f76a4d40a0f88a0a0/operator/test/test.sh#L106 and the use of `--ignore-not-found` you should not see that error now.

**Comment by gabemontero** [comment]
More proof needing the rebase - in your passing `tests-post-upgrade` over in https://console-openshift-console.apps.pipeline-stage.3jhu.p1.openshiftapps.com/k8s/ns/pipeline-service-ci/tekton.dev~v1beta1~PipelineRun/pipeline-service-upgrade-test-95xvm/logs/tests-post-upgrade you still have the old output with no pod names:

```
[security]
 - Check security: 
  - Check Pod Security openshift-pipelines: 
   - OK pod security for openshift-pipelines
  - Check Pod Host Network openshift-pipelines: 
   - OK hostIPC settings for openshift-pipelines
   - OK hostPID settings for openshift-pipelines
   - OK hostNetwork settings for openshift-pipelines
  - Check Pod Security tekton-results: 
   - OK pod security for tekton-results
  - Check Pod Host Network tekton-results: 
   - OK hostIPC settings for tekton-results
   - OK hostPID settings for tekton-results
   - OK hostNetwork settings for tekton-results
  - Check Pod Security tekton-chains: 
   - OK pod security for tekton-chains
  - Check Pod Host Network tekton-chains: 
   - OK hostIPC settings for tekton-chains
   - OK hostPID settings for tekton-chains
   - OK hostNetwork settings for tekton-chains
```

**Review by gabemontero — APPROVED** [review]
we are good to go

both @sayan-biswas and I monitored the CI live, including logging into the test cluster and confirming the rollout, use of upgrade levels, main branch levels, etc.

**Pull request merged**
