### PR TITLE
remove panel using faulty upstream latency metric

### PR DESCRIPTION
**Pull request by gabemontero**
per my detailing in https://docs.google.com/document/d/1NkzOm1cquseD8S6sRk1AVX7eOrdFgSA47-58diz6twM/edit#heading=h.m42fpveco6y0 has proven unreliable and we have better replacements in the exporter

pipelinerun_gap_between_taskruns_milliseconds
taskrun_pod_duration_kubelet_acknowledged_milliseconds
taskrun_pod_duration_kubelet_to_container_start_milliseconds

fwiw I am the one who originally suggested we had a panel using this metric; I am backing off of that

### CODE REVIEW

**Review by Roming22 — COMMENTED** [review]
OK to remove the dashboard, as the metric is unreliable and we have a replacement.

**Review by Roming22 — APPROVED** [review]

**Comment by gabemontero** [comment]
ok this time the deployment tests passed but the upgrade one failed
last time the upgrade passed but one of the deployment tests failed

I'm going to do one more retest @ramessesii2 @Roming22 to see if there is any consistency in the failure; and of course catch the full logs before the pipelinerun is pruned (I need to revisit @sayan-biswas 's results SOP and get that log inspection process more ingrained in my day to day process).

we know a grafana dashboard change has no effect here, but if we have some consistent CI fragility here outside of cluster setup stuff I'll try and capture it

otherwise I'm merging this and moving on

**Comment by gabemontero** [comment]
and now they all ran clean ;-) ..... confirmed "flakes"

merging

**Pull request merged**
