### PR TITLE
Fix tekton results structure

### PR DESCRIPTION
**Pull request by sayan-biswas**
## Changes
- Simplify tekton results folder structure 
- Add service monitor config.

### CODE REVIEW

**Review by avinal — APPROVED** [review]
Looks good to me

**Comment by gabemontero** [comment]
OK @sayan-biswas we have to remember that after this merges, rather than using the auto-generated PR to update infra-deployments, you have to create a manual version of that PR, where you include the same changes it has, but also remove the servicemonitor currently being created in infra-deployments

**Comment by sayan-biswas** [comment]
@gabemontero Yes. Need to remove the service monitor components there and update the kustomize.

**Pull request merged**
