### PR TITLE
Revert tls patch to fix connection tekton-result api and Minio S3

### PR DESCRIPTION
**Pull request by AndrienkoAleksandr**
# Related pr

https://github.com/openshift-pipelines/pipeline-service/pull/545

### CODE REVIEW

**Review by Roming22 — APPROVED** [review]
@Mo3m3n If you don't have any comments, please merge.

**Comment by Mo3m3n** [comment]
@AndrienkoAleksandr currently connections between tekton-results-api and Minio s3 are working since results-api returns the expected result (records and logs) in the corresponding e2e test.
So we need to understand why this patch is needed. I will try to have a look this week

**Comment by adambkaplan** [comment]
@Mo3m3n the current e2e test can be best described as a smoke test - it verifies the API is available and is not returning an error result, but that is it. In my own demo from last sprint, the actual log data we are looking for does not exist in the record.

I am helping @avinal refine https://issues.redhat.com/browse/PLNSRVCE-1182 - we hope to run the "upstream" e2e test for Results, potentially in parallel with the other pipeline service tests.

**Comment by AndrienkoAleksandr** [comment]
I found one more bug reproducible in the slowly clusters: init container doesn't fail when minio route is not ready, because in the entrypoint shell command was used `;` separator instead of `&&`. So I included this fix to this pr.

**Pull request merged**
