### PR TITLE
HOLD:  PLNSRVCE-1105: reenable pac to update placement svc shas in infra-deployments

### PR DESCRIPTION
**Pull request by gabemontero**
If my earlier diagnosis is correct, once https://github.com/redhat-appstudio/infra-deployments/pull/1836 and something akin to https://github.com/redhat-appstudio/build-definitions/pull/402 merge, no longer needing shared resources could mean this job will work even if our CI is not yet running on the full RHTAP cluster

### CODE REVIEW

**Comment by gabemontero** [comment]
my guess is @Roming22 it was too soon for merging this given what I stated in the description

Watching https://console-openshift-console.apps.pipeline-stage.3jhu.p1.openshiftapps.com/k8s/ns/pipeline-service-ci/tekton.dev~v1beta1~PipelineRun/pipeline-service-push-xdfz2/logs

**Comment by Roming22** [comment]
I got confused and pressed merge in the wrong tab. I'll revert the PR right away.

**Comment by Roming22** [comment]
Reverted by #653

**Pull request merged**
