### PR TITLE
Temporarily adjusted the max_retries to ensure CI complete successfully

### PR DESCRIPTION
**Pull request by xinredhat**
Because the ROSA HCP cluster is taking longer than we anticipated, we temporarily adjusted the max_retries to ensure ROSA HCP cluster creation completes successfully

### CODE REVIEW

**Comment by Roming22** [comment]
Run failed with `Operator console is not available` after 20 retries. I'll trigger another round to see what happens.

**Comment by Roming22** [comment]
@xinredhat Can this be closed?

**Comment by xinredhat** [comment]
> @xinredhat Can this be closed?

sure, I will close it.

**Comment by xinredhat** [comment]
closed. ROSA HCP looks good now.

**Pull request closed without merging**
