### PR TITLE
remove embedded-status from tekton-config

### PR DESCRIPTION
**Pull request by avinal**
- Refer: PLNSRVCE-1299

Signed-off-by: Avinal Kumar <avinal@redhat.com>

### CODE REVIEW

**Comment by ramessesii2** [comment]
Hi @avinal, although looking at `PLNSRVCE-1299`, the purpose of this PR is clear to me but considering Pipeline-Service an open-source repo, IMO it will be good idea to at least briefly explain/copy-paste the purpose/impact in the PR description. Hopefully I make sense to you.

**Comment by avinal** [comment]
/hold

I will be modifying this PR according to discussion in the stand up call.

**Review by Roming22 — APPROVED** [review]

**Comment by Roming22** [comment]
pipeline-service-test seems to be flaky because of hypershift. Forcing merge.

**Pull request merged**
