### PR TITLE
Create a CronJob to fix RHTAPBUGS-256

### PR DESCRIPTION
**Pull request by Roming22**
This fix is temporary and meant to be reverted once the issue is solved in PaC.

### CODE REVIEW

**Review by gabemontero — APPROVED** [review]

**Comment by ramessesii2** [comment]
3 out of the 6 tests fail due to 
```
task deploy-cluster has the status "Failed":

- name: kube-rbac-proxy
    version: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:b49924605e1ceb4a020ad724f862c9690ca1a5ed99f936cfe1cc150d322a53e6
+ exit 1
```
/retest

**Review by ramessesii2 — APPROVED** [review]

**Pull request merged**
