### PR TITLE
update tekton-results manifests to use overlays

### PR DESCRIPTION
**Pull request by avinal**
## Changes
- remove database patches
- replace resource with base-only overlay
- Refer PLNSRVCE-1256

Signed-off-by: Avinal Kumar <avinal@redhat.com>

### CODE REVIEW

**Review by enarha — APPROVED** [review]

**Review by sayan-biswas — COMMENTED** [review]
Please add the following config as `true`
https://github.com/tektoncd/results/blob/e85794158c43defca77deb2b63201497dca9f45d/config/base/env/config#L10

Also, hold on for PR #710 to get merged, because there are some folder changes.

**Comment by avinal** [comment]
@sayan-biswas I have rebased and updated the config. PTAL

**Review by sayan-biswas — APPROVED** [review]

**Comment by gabemontero** [comment]
So the test failures are from the known hypershift issue.  And we have sufficient permissions here.

That said, given the nature of these changes, and the updates that transpired since the last test, we need to wait until the hypershift stuff is sorted out, and we can retest successfully.

**Comment by gabemontero** [comment]
oops ... aside from the hypershift issues RHTAP and other groups were hitting, we have a separate problem, using an out of date OCP version:

```
  Provision ROSA with HCP cluster...
+ rosa create cluster --cluster-name ci-1369f1a090 --sts --mode=auto --oidc-config-id 24132snjs8gktc5rtufqv8hggjv3ivbt --operator-roles-prefix plnsvc-ci --region us-east-1 --version 4.12.16 --compute-machine-type m5.2xlarge --subnet-ids=subnet-001487732ebdd14f4,subnet-0718fb663f4b97f38,subnet-0fe426997da62662c --hosted-cp -y
ERR: Expected a valid OpenShift version: A valid version number must be specified
Valid versions: 4.12.22 4.12.21
```

I'll see if I can update this in @xinredhat 's absence

**Comment by gabemontero** [comment]
you need to rebase this PR off of the latest main branch @avinal to pick up my fix from https://github.com/openshift-pipelines/pipeline-service/pull/712 so that the rosa install on the tests work

the latest retest still has the old use of 4.12.16

**Comment by gabemontero** [comment]
ok progress on the tests ... no more rosa issue

@avinal I assume you saw, the failure on the upgrade tests seem results related.  During the downgrade portion:

```
- Test logs: Failed
[ERROR] Unable to retrieve logs for 20ee46a5-d471-4f6f-bf87-85ad176cede9 from pipeline run pipelinerun.tekton.dev/test-pipelinerun-v89rb
```

I'll 

/retest

to see if it is a flake, or related to your change.

**Comment by gabemontero** [comment]
yeah the downgrade is still failing @avinal 

the full log before it gets pruned:

```
step-run-tests
+ echo 'Start executing pipeline cases ...'
Start executing pipeline cases ...
++ find /workspace/source -type f -name test.sh -exec dirname '{}' +
+ TEST_DIR=/workspace/source/operator/test
+ /workspace/source/operator/test/test.sh --kubeconfig /workspace/kubeconfig-dir/kubeconfig
[Setup]
  - Namespace configuration: OK

[chains]
  - Run pipeline: OK
  - Pipeline signed: OK
  - Image signed: Skip
  - Public key: OK


[pipelines]
  - Run pipeline: OK

[results]
  - Run pipeline: OK
  - Results in database:
    - Test records: Failed
[ERROR] Unable to retrieve records for 448c1c70-f2bc-4ae7-b014-67abac2cb61a from pipeline run pipelinerun.tekton.dev/test-pipelinerun-7nmpp
```

you all need to sort out @avinal @sayan-biswas @enarha what changed in the downstream bump that is causing this,
such that when we go back to the prior version, it fails.

- a bug that needs to be fix?
- an unrelated bug that we are hitting consistently now?
- or do we need some new converstion logic to compensate, similar to what occurred when we had our upgrade issue a few months back?

thanks

**Comment by avinal** [comment]
@gabemontero I will take a look on Monday. IMO nothing breaking has changed because the first few times when the PR tests were run, it was successful. After rebase it is failing.

**Comment by sayan-biswas** [comment]
@gabemontero It's not related I guess. All the tests passed now. 
Maybe the pruner timing issue that @ramessesii2 was facing few days ago.

**Comment by gabemontero** [comment]
> @gabemontero It's not related I guess. All the tests passed now. Maybe the pruner timing issue that @ramessesii2 was facing few days ago.

interesting .... now that you all mention this @sayan-biswas , looking at https://github.com/openshift-pipelines/pipeline-service/blob/main/operator/test/test.sh#L278-L340 I do not see any retry on the REST query.

if there are windows were pruning would impact results, feels like we need retry in that part of the test.

does that sound correct to you all @avinal @ramessesii2 @enarha @sayan-biswas ?  if so, can one of you all make an attempt at adding that retry?

thanks

**Pull request merged**
