### PR TITLE
Remove deprecated images from operator

### PR DESCRIPTION
**Pull request by Roming22**
Those images have been deprecated when KCP was abandonned. The content used for local development and has been moved to the 'developer' directory.

* Remove access-setup image.
* Remove cluster-setup image.
* OpenShift GitOps operator updated to 1.5.10.
* Refactor dev_setup.sh: * Split the content into multiple files (one file per app). * Use a 'local' folder as the template to deploy pipeline-service

### CODE REVIEW

**Review by gabemontero — APPROVED** [review]
conceptually lgtm

not sure I can speak to the nuances of the bash changes, and what were deltas vs. copy / paste to new files

multiple commits capturing "copy as is to new file" vs. "here is where I tweaked things after the copy" could have been helpful

**Comment by gabemontero** [comment]
> conceptually lgtm
> 
> not sure I can speak to the nuances of the bash changes, and what were deltas vs. copy / paste to new files
> 
> multiple commits capturing "copy as is to new file" vs. "here is where I tweaked things after the copy" could have been helpful

admittedly I may have had opportunities for that in the recent exporter reorg :-)

**Comment by gabemontero** [comment]
it seems at least conceivable @Roming22 the upgrade job failure in the upgrade-pipeline-service step is related to some of these change (given the bash changes ??)

```
Please commit your changes or stash them before you switch branches.
Aborting
command terminated with exit code 1
```

**Comment by Roming22** [comment]
Failure logs:
```
STEP-RUN-PLNSVC-SETUP

+ touch /workspace/workdir/source/destroy-cluster.txt
+ echo 'Execute dev_setup.sh script to set up pipeline-service ...'
Execute dev_setup.sh script to set up pipeline-service ...
+ kubectl -n default exec pod/ci-runner -- sh -c '/workspace/sidecar/bin/plnsvc_setup.sh https://github.com/openshift-pipelines/pipeline-service 0f2d7aaa82f8a992816e5062f6f261d8beeb70a7'
+ export KUBECONFIG=/kubeconfig
+ KUBECONFIG=/kubeconfig
+ REPO_URL=https://github.com/openshift-pipelines/pipeline-service
+ REPO_REVISION=0f2d7aaa82f8a992816e5062f6f261d8beeb70a7
+ git config --global --add safe.directory /workspace/source
+ git fetch origin 0f2d7aaa82f8a992816e5062f6f261d8beeb70a7
From https://github.com/openshift-pipelines/pipeline-service
 * branch            0f2d7aaa82f8a992816e5062f6f261d8beeb70a7 -> FETCH_HEAD
+ git checkout 0f2d7aaa82f8a992816e5062f6f261d8beeb70a7
error: Your local changes to the following files would be overwritten by checkout:
	developer/config.yaml
Please commit your changes or stash them before you switch branches.
Aborting
command terminated with exit code 1
```

Issue should be fixed by forcing the checkout in `ci/images/ci-runner/hack/sidecar/bin/plnsvc_setup.sh`.

**Pull request merged**
